name : "Ionic CI"

on:
  push:
    branches:
      - master
jobs :
  build:
    name: build
    concurrency: staging_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v1
      - run :
          npm ci
          npm run all
  test:
    name : test
    needs: build
    runs-on: ubuntu-latest
    concurrency: staging_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Use coturiv/setup-ionic
        uses: ./
      - name: run Cordova project tests
        run : |
          ionic start testapp blank --cordova --type angular --no-link --no-git --no-interactive --confirm
          cd testapp
          ionic cordova platform add android@latest
          ionic cordova build android
